---
title: "Reproducibility Report for Study 4 and 5 by Boyce, Levy, and Futrell (2019, Journal of Memory and Language)"
author: "Jaylen Pittman (jaylen@stanford.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: false
---

<!-- Reproducibility reports should all use this template to standardize reporting across projects. These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

## Introduction

**Clarify key analysis of interest here**  
The authors find that using an Automating version of the Maze task by generating distractor words with LSTM language models results in greater statistical power and localization of incremental processing effects when compared to Self-Paced Reading and Maze tasks with manually coded distractors.

### Justification for choice of study

Boyce and colleagues provide compelling evidence for the use of A-Maze in psycholinguistic experiements involving incremental processing, such as reading text on a screen. My own research investigates incremental reading processes and the effects of stereotyped language on processing outcomes via the same measures that Boyce and colleagues investigate, which is `surprisal`, or the negative log probability of a word `w` given a preceding context  (w<sub>1</sub>...w<sub>i</sub> ). I want to replicate the results of the A-Maze experiments because I plan to employ A-Maze in my own experiments and want to acquaint myself analytic pipeline. Along the way I can assess the validity of the results in the experiments. 

### Anticipated challenges

Mostly, I think it will take some time to train the language models on a local machine (I trained one of the models before and it took a while). I also wonder how consistent the distractor generation will be given different machines, etc. I expect the LSTMs to be a little finicky. I also expect that it will take some time to get fully up and running with Ibex, since I am a little rusty there. However, the authors seem to have done a great job documenting their processes/pre-registrations/etc. so I think I am fortunate in that regard.

### Links

Project repository (on Github): <https://github.com/psych251/boycefutrelllevy2020/tree/main>
Original paper (as hosted in your repo): 
<https://github.com/psych251/boycefutrelllevy2020/tree/main/original_paper>

## Methods

### Description of the steps required to reproduce the results

Please describe all the steps necessary to reproduce the key result(s) of this study. 

### Differences from original study

Explicitly describe known differences in the analysis pipeline between the original paper and yours (e.g., computing environment). The goal, of course, is to minimize those differences, but differences may occur. Also, note whether such differences are anticipated to influence your ability to reproduce the original results.

## Project Progress Check 1

### Measure of success

Please describe the outcome measure for the success or failure of your reproduction and how this outcome will be computed.


### Pipeline progress

Earlier in this report, you described the steps necessary to reproduce the key result(s) of this study. Please describe your progress on each of these steps (e.g., data preprocessing, model fitting, model evaluation).


## Results

### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
### Data Preparation

#### Load Relevant Libraries and Functions

#### Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Key analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

###Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Reproduction Attempt

Open the discussion section with a paragraph summarizing the primary result from the key analysis and assess whether you successfully reproduced it, partially reproduced it, or failed to reproduce it.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis of the dataset, (b) assessment of the meaning of the successful or unsuccessful reproducibility attempt - e.g., for a failure to reproduce the original findings, are the differences between original and present analyses ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the reproducibility attempt (if you contacted them).  None of these need to be long.
